name: Build & Push Docker Images

on:
  push:
    branches:
      - master
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code du repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Se connecter à Docker Hub avec les secrets GitHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Build image backend
      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tp-backend:latest ./springboot

      # 4) Build image frontend
      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tp-frontend:latest ./angular-app

      # 5) Push backend vers Docker Hub
      - name: Push backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tp-backend:latest

      # 6) Push frontend vers Docker Hub
      - name: Push frontend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tp-frontend:latest

      # 7) Tester avec docker-compose
      - name: Test app with docker-compose
        run: |
          docker-compose up -d
          sleep 10
          docker ps

      # 8) Test backend API
      - name: Test backend
        run: curl -I http://localhost:8080

      # 9) Test frontend
        # pour Angular en mode dev (ng serve)
      - name: Test frontend
        run: curl -I http://localhost:4200

      # 10) Shutdown containers
      - name: Stop app
        run: docker-compose down
``
